config/routes.rb
Rails.application.routes.draw do

  resources :polls
  root to: 'polls#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_fail'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out

  
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :vote_options, dependent: :destroy
  validates :topic, presence: true


  accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true
  #:reject_if => :all_blank raises an error and rejects saving the poll if it has no vote options.
  #:allow_destroy => true allows users to delete vote options through nested attributes (when opening
  #an Edit poll page, which we will create shortly).

end

app/models/user.rb
class User < ActiveRecord::Base

  class << self
    def from_omniauth(auth)
      uid = auth.uid
      info = auth.info.symbolize_keys!
      user = User.find_or_initialize_by(uid: uid)
      user.name = info.name
      user.image_url = info.image
      user.save!
      user
    end
  end

end

app/models/vote_option.rb
class VoteOption < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :poll
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: cookies[:user_id]) if cookies[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(poll_params)
    if @poll.save
      flash[:success] = "Poll was created!"
      redirect_to polls_path
    else
      render 'new'
    end
  end

  def show 
    @poll = Poll.find_by_id(params[:id])
  end

  def edit
    @poll = Poll.find_by_id(params[:id])
  end
   
  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      flash[:success] = 'Poll was updated!'
      redirect_to polls_path
    else
      render 'edit'
    end
  end
   
  def destroy
    @poll = Poll.find_by_id(params[:id])
    if @poll.destroy
      flash[:success] = 'Poll was destroyed!'
    else
      flash[:warning] = 'Error destroying poll...'
    end
    redirect_to polls_path
  end
  
  private

  def poll_params
    params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :_destroy])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create 
    user = User.from_omniauth(request.env['omniauth.auth'])
    cookies[:user_id] = user.id 
    flash[:success] = "Welcome, #{user.name}!"
    redirect_to root_url
  end

  def destroy
    cookies.delete(:user_id)
    flash[:success] = "Goodbay!"
    redirect_to root_url
  end

  def auth_fail
    render text: "You've tried to authenticate via #{params[:strategy]}, but the following error
    occurred: #{params[:message]}", status: 500
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Poller', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Add poll', new_poll_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= image_tag current_user.image_url, alt: current_user.name %></li>
          <li><%= link_to 'Logout', sign_out_path %></li>
        <% else %>
          <li><%= link_to 'Sign in', '/auth/facebook' %></li>
        <% end %>
      </ul>
    </div>
  </div>
   
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
   
    <div class="page-header">
      <h1><%= yield :page_header %></h1>
    </div>
   
    <%= yield %>
  </div>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for @poll do |f| %>
  <%= render 'shared/errors', object: @poll %>

  <div class="form-group">
    <%= f.label :topic %>
    <%= f.text_area :topic, rows: 3, required: true, class: 'form-control' %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">Options</div>
    <div class="panel-body">
      <%= f.fields_for :vote_options do |options_form| %>
        <%= render 'vote_option_fields', f: options_form %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add option', f, :vote_options %>
      </div>
    </div>
  </div>

  <%= f.submit 'Create', class: 'btn btn-primary btn-lg '%>
<%end%>

app/views/polls/_vote_option_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>
  <%= link_to_remove_association "remove option", f %>
</div>

app/views/polls/edit.html.erb
<% content_for(:page_header) {"Edit poll"} %>

<%= render 'form' %>

app/views/polls/index.html.erb
<% content_for(:page_header) {"Participate in our polls right now! "} %>

<% @polls.each do |poll| %>
  <div class="well">
    <h2><%= poll.topic %></h2>

    <p>
      <% if current_user %>
        <%= link_to 'Participate!', poll_path(poll), class: 'btn btn-primary btn-lg block'%>
      <% else %>
        Please sign in via <%= link_to 'Facebook', '/auth/facebook' %> to participate in this poll.
      <% end %>
    </p>

    <div class="btn-group">
      <%= link_to 'Edit', edit_poll_path(poll), class: "btn btn-default" %>
      <%= link_to 'Delete', poll_path(poll),
        mothod: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?"} %>
    </div>
  </div>
<% end %>

app/views/polls/new.html.erb
<% content_for(:page_header) {"Create a new Poll"} %>

<%= render 'form' %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
    <h4> The following errors were found:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<%end%>